name: Build Windows ONEDIR

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.11"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller requests

      - name: Download DeepDanbooru Model
        run: |
          mkdir model
          curl -L -o model.zip https://github.com/KichangKim/DeepDanbooru/releases/download/v3-20211112-sgd-e28/deepdanbooru-v3-20211112-sgd-e28.zip
          tar -xf model.zip 2>nul || powershell Expand-Archive model.zip -DestinationPath .
          for /d %%i in (deepdanbooru-*) do xcopy "%%i\*" model\ /E /H /Y

      - name: Build ONEDIR
        run: |
          pyinstaller --clean app.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/app/
