name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install tensorflow-cpu
          pip install tensorflow-io
          pip install deepdanbooru
          pip install nudenet

      - name: Build EXE
        run: pyinstaller app.py --noconfirm --clean --onedir --windowed --collect-all tensorflow --collect-all tensorflow_io --collect-all deepdanbooru --collect-all nudenet

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/app/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/app/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
